services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=s3cr3t
    ports:
      - "5435:5432"
    volumes:
      - ./data/db/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  alembic:
    build:
      context: ./
      dockerfile: ./alembic/Dockerfile
    environment:
      - CHAI_DATABASE_URL=postgresql://postgres:s3cr3t@db:5432/chai
      - PGPASSWORD=s3cr3t
    depends_on:
      db:
        condition: service_healthy
    working_dir: /alembic
    entrypoint: ["./run_migrations.sh"]

  pipeline:
    build:
      context: ./
      dockerfile: ./src/Dockerfile
      args:
        BUILDKIT_PROGRESS: plain
    environment:
      - CHAI_DATABASE_URL=postgresql://postgres:s3cr3t@db:5432/chai
      - FREQUENCY=${FREQUENCY:-24}
      - PYTHONPATH=/
      - PKG_MANAGER=${PKG_MANAGER:-crates}
      - TEST=${TEST:-false}
      - DEBUG=${DEBUG:-true}
      - FETCH=${FETCH:-true}
    depends_on:
      db:
        condition: service_healthy
      alembic:
        condition: service_completed_successfully
    working_dir: /src
    entrypoint: ["./run_pipeline.sh"]

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:s3cr3t@db:5432/chai
      - HOST=0.0.0.0
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      alembic:
        condition: service_completed_successfully
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  monitor:
    build: monitor
    environment:
      - DOCKER_HOST=${DOCKER_HOST:-unix:///var/run/docker.sock}
    volumes:
      - ./monitor:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      pipeline:
        condition: service_started
    working_dir: /usr/src/monitor
    entrypoint: ["./run_monitor.sh"]
